[tool.poetry]
name = "stimela"
version = "2.0rc2"
description = "Framework for system agnostic pipelines for radio interferometry arrays"
authors = ["Sphesihle Makhathini <sphemakh@gmail.com>", "Oleg Smirnov and RATT <osmirnov@gmail.com>"]
readme = "README.rst"
license = "GNU GPL v2"
packages = [{ include = "stimela" }, {include = "scabha"}, {include= "tests" }]
#include = [{ path = "tests" }]

[tool.poetry.dependencies]
python = "^3.7"
munch = "^2.5.0"
omegaconf = "^2.1"
click = "^8.1.3"
pyparsing = "^3.0.9"
pydantic = "^1.10.2"
pathos = "^0.3.0"
psutil = "^5.9.3"
rich = "^12.6.0"

[tool.poetry.scripts]
stimela = "stimela.main:cli"

[build-system]
requires = ["setuptools", "poetry-core"]
build-backend = "poetry.core.masonry.api"



[tool.poetry.group.tests]
optional = true
[tool.poetry.group.tests.dependencies]
pytest = "^7.1.3"
flake8 = "*"

[tool.poetry.group.docs]
optional = true
[tool.poetry.group.docs.dependencies]
Sphinx = "^5.3.0"
sphinx-copybutton = "^0.5.0"
furo = "^2022.9.15"

