[tool.poetry]
name = "stimela"
version = "2.0rc2"
description = "Framework for system agnostic pipelines for radio interferometry arrays"
authors = ["Sphesihle Makhathini <sphemakh@gmail.com>", "Oleg Smirnov and RATT <osmirnov@gmail.com>"]
readme = "README.rst"
license = "GNU GPL v2"
packages = [{ include = "stimela" }]
include = [{ path = "tests" }]

[tool.poetry.dependencies]
python = "^3.7"
munch = "^2.5.0"
omegaconf = "^2.1"
click = "^8.1.3"
pyparsing = "^3.0.9"
pydantic = "^1.10.2"
pathos = "^0.3.0"
psutil = "^5.9.3"
rich = "^12.6.0"
flake8 ={version="^5.0.4", optional=true}
pytest = {version="^7.1.3", optional=true}
Sphinx = {version="^5.1.1", optional=true}
sphinx-copybutton = {version="^0.5.0", optional=true}
furo = {version="^2022.9.15", optional=true}

[tool.poetry.scripts]
stimela = "stimela.main:cli"

[build-system]
requires = ["setuptools", "poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
testing = ["pytest", "flake8"]
docs = ["Sphinx", "sphinx-copybutton", "furo"]

